#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

project_dir="$( cd "$(dirname "$0")/.." >/dev/null 2>&1 ; pwd -P )"
readonly project_dir
readonly target_dir="$project_dir/target"
readonly extension_config="$project_dir/extension/src/extension-description.ts"

readonly all_built_files=("$target_dir"/exasol-cloud-storage-extension-*.jar)
readonly file_count=${#all_built_files[@]}

if [ "$file_count" -ne 1 ]; then
    echo "ERROR: Expected exactly one jar but found $file_count in $target_dir: ${all_built_files[*]}"
    exit 1
fi

readonly complete_path="${all_built_files[0]}"
file_name=$(basename "$complete_path")
readonly file_name
file_size_bytes=$(stat -c%s "$complete_path")
readonly file_size_bytes

version=
if [[ $file_name =~ ^exasol-cloud-storage-extension-(.*).jar$ ]]; then
    version=${BASH_REMATCH[1]}
else
    echo "ERROR: Could not extract version from filename $file_name"
    exit 1
fi
readonly version

cat > "$extension_config" <<EOL
// Generated by $0
export const EXTENSION_DESCRIPTION = {
    fileName: "${file_name}",
    fileSizeBytes: ${file_size_bytes},
    version: "${version}"
}
EOL

echo "Generated extension config $extension_config:"
echo "File name: ${file_name}, size: ${file_size_bytes} bytes, version: ${version}"
