sources:
  - type: maven
    path: pom.xml
    modules:
      - jar_artifact
      - integration_tests
linkReplacements:
  - "http://wiki.fasterxml.com/JacksonModuleScala|https://github.com/FasterXML/jackson-module-scala"
  - "https://netty.io/netty-all/|https://netty.io/"
  - "https://www.alluxio.io/alluxio-core/alluxio-core-client/alluxio-core-client-hdfs/|https://www.alluxio.io"
  - "https://developers.google.com/protocol-buffers/protobuf-java/|https://github.com/protocolbuffers/protobuf/tree/main/java"
  - "https://github.com/GoogleCloudPlatform/BigData-interop/gcs-connector/|https://github.com/GoogleCloudDataproc/hadoop-connectors/tree/master/gcs"
  - "https://github.com/googleapis/google-oauth-java-client/google-oauth-client|https://github.com/googleapis/google-oauth-java-client"
  - "https://orc.apache.org/orc-core|https://orc.apache.org/"
  - "http://jackson.codehaus.org|https://github.com/codehaus/jackson"
  - "http://nexus.sonatype.org/oss-repository-hosting.html/scalatest-maven-plugin|https://github.com/scalatest/scalatest-maven-plugin"
excludes:
  - "E-PK-CORE-18: Outdated content: '.github/workflows/ci-build.yml'"
  - "E-PK-CORE-18: Outdated content: '.github/workflows/ci-build-next-java.yml'"
  - "E-PK-CORE-18: Outdated content: '.github/workflows/release_droid_upload_github_release_assets.yml'"
  - "E-PK-CORE-18: Outdated content: '.github/workflows/release_droid_prepare_original_checksum.yml'"
  - regex: "(?s)E-PK-CORE-53: The dependencies.md file has outdated content.*"
