sources:
  - type: maven
    path: pom.xml
    modules:
      - jar_artifact
      - integration_tests
  - type: npm
    path: extension/package.json
    artifacts:
      - dist/cloud-storage-extension.js
version:
  fromSource: pom.xml
linkReplacements:
excludes:
  # Project is written in Scala, no need to test with next Java version
  - "E-PK-CORE-18: Outdated content: '.github/workflows/ci-build-next-java.yml'"
build:
  runnerOs: ubuntu-22.04
  freeDiskSpace: true
  exasolDbVersions:
    - "2025.2.1"
    - "2025.1.10"
# Disabled, see this for details: https://github.com/exasol/cloud-storage-extension/issues/356
#    - "7.1.30"
  workflows:
    - name: ci-build.yml
      stepCustomizations:
        - action: INSERT_AFTER
          job: matrix-build
          stepId: enable-testcontainer-reuse
          content:
            name: Build extension
            id: build-extension
            run: |
              # Packaged JAR is required for building the extension
              mvn --batch-mode package -DossindexSkip=true -DskipTests
              cd extension
              npm ci --ignore-scripts
              npm run build
              npm run test
              npm run lint
        - action: INSERT_AFTER
          job: matrix-build
          stepId: build-extension
          content:
            name: Fix VM Crash in UDFs
            id: fix-vm-crash
            run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

    - name: release.yml
      stepCustomizations:
        - action: INSERT_AFTER
          stepId: verify-release
          content:
            name: Build extension
            id: build-extension
            run: |
              # Packaged JAR is required for building the extension
              mvn --batch-mode package -DossindexSkip=true -DskipTests -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
              cd extension
              npm ci --ignore-scripts
              npm run build
