name: Extension CI Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: "extension/package-lock.json"
      - name: Install dependencies
        run: cd extension && npm ci
      - name: Run tests
        run: |
          cd extension
          echo 'export const EXTENSION_DESCRIPTION = {' \
               '  fileName: "exasol-cloud-storage-extension-2.7.3.jar",' \
               '  fileSizeBytes: 572096955,' \
               '  version: "2.7.3"' \
               '}' >> src/extension-description.ts
          npm test
      - name: Run build
        run: cd extension && npm run build
      - name: Run linter
        run: cd extension && npm run lint
