name: CI Build next Java

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  java-17-compatibility:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
      - name: Run tests and build with Maven
        run: |
          mvn --batch-mode --update-snapshots clean javadoc:javadoc -DtrimStackTrace=false \
              -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
