name: Release Droid - Prepare Original Checksum

on:
  workflow_dispatch:

env:
  DEFAULT_DOCKER_DB_VERSION: "7.1.21"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'maven'
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Enable testcontainer reuse
        run: echo 'testcontainers.reuse.enable=true' > "$HOME/.testcontainers.properties"
      - name: Run tests and build with Maven
        run: |
          mvn --batch-mode clean verify --file pom.xml \
              -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
              -DtrimStackTrace=false \
              -Dcom.exasol.dockerdb.image=${{ env.DEFAULT_DOCKER_DB_VERSION }}
        env:
          EXASOL_DOCKER_VERSION: ${{ env.DEFAULT_DOCKER_DB_VERSION }}
      - name: Prepare checksum
        run: find target -maxdepth 1 -name *.jar -exec sha256sum "{}" + > original_checksum
      - name: Upload checksum to the artifactory
        uses: actions/upload-artifact@v3
        with:
          name: original_checksum
          retention-days: 5
          path: original_checksum
